### ISSUE TITLE
Find a way to support remote image embeds in markdown content

### ISSUE THREAD

**Issue by AdmiralPotato** [801labs/801labs.org#23]
The ability to just paste image data into the GitHub Markdown editor is pretty great, linking non-local assets breaks the build at the moment. Find a way to make it work.

Input:
![image](https://user-images.githubusercontent.com/820844/144165223-02dc71c0-576b-481b-80bc-3103b79bb020.png)

Build Error:
```
...
Automatically optimizing pages...

Error occurred prerendering page "/research-portal/post/writing-research-posts". Read more: https://err.sh/next.js/prerender-error
Error: Cannot find module './https://user-images.githubusercontent.com/5651603/140208036-1b923b0a-2791-4c1a-8928-9db18339d9c9.png'
    at webpackContextResolve (/home/runner/work/801labs.org/801labs.org/.next/server/pages/about.js:1910:11)
    at webpackContext (/home/runner/work/801labs.org/801labs.org/.next/server/pages/about.js:1905:11)
    at /home/runner/work/801labs.org/801labs.org/.next/server/pages/about/news/post/[slug].js:793:46
    at overload (/home/runner/work/801labs.org/801labs.org/node_modules/unist-util-visit/index.js:27:12)
    at one (/home/runner/work/801labs.org/801labs.org/node_modules/unist-util-visit-parents/index.js:34:25)
    at all (/home/runner/work/801labs.org/801labs.org/node_modules/unist-util-visit-parents/index.js:57:16)
    at one (/home/runner/work/801labs.org/801labs.org/node_modules/unist-util-visit-parents/index.js:42:28)
    at all (/home/runner/work/801labs.org/801labs.org/node_modules/unist-util-visit-parents/index.js:57:16)
    at one (/home/runner/work/801labs.org/801labs.org/node_modules/unist-util-visit-parents/index.js:42:28)
    at all (/home/runner/work/801labs.org/801labs.org/node_modules/unist-util-visit-parents/index.js:57:16)

...
```

**Comment by miketweaver** [comment]
It'll probably accept <img> tags

**Comment by AdmiralPotato** [comment]
All you need to do to edit an article on our site is the in-browser VSCode, which can be activated by pressing `.` on a keyboard on the repo's GitHub page. I don't think we need this feature anymore. The in-browser VSCode supports working in branches and file uploads, so it meets all these needs. Closing ticket.
